# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
encoding: utf-8
title:            Deniz Eren
tagline:          'An ordinary person'
description:      'To follow the path:</br>look to the master,</br>follow the master,</br>walk with the master,</br>see through the master,</br>become the master.</br></br>Zen Proverb'
url:              http://blog.denizeren.net
baseurl:          '/'
paginate:         5

author:
  name:           'Deniz Eren'
  url:            http://denizeren.net

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
